version: '3.7'

services:

  db:
    image: 'mongo:3.6'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    restart: 'unless-stopped'

  app:
    build:
      dockerfile: 'app.Dockerfile'
      context: '.'
    ports:
      - "8080:8080"
    depends_on:
      - 'web-api'
      - 'db'

  web-api:
    build:
      dockerfile: 'web-api.Dockerfile'
      context: '.'
    ports:
      - '5000:5000'
